baseURL = "https://hmmdeif.github.io/empiresmod-website/"
languageCode = "en-us"
title = "Empires"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
