name: Send a Tweet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: log
        run: |
          POST_COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B)
          echo ::set-output name=POST_COMMIT_MESSAGE::$POST_COMMIT_MESSAGE
          if [[ $POST_COMMIT_MESSAGE == *"Tweet: "* ]]; then HAS_TWEET=true ; fi
          echo ::set-output name=HAS_TWEET::$HAS_TWEET

      - id: parse
        if: steps.log.outputs.HAS_TWEET
        run: |
          searchString="Tweet: "
          POST_COMMIT_MESSAGE="${{ steps.log.outputs.POST_COMMIT_MESSAGE }}"
          tweet=${POST_COMMIT_MESSAGE#*$searchString}
          echo ::set-output name=TWEET::$tweet

      - uses: nearform-actions/github-action-notify-twitter@v1
        if: steps.log.outputs.HAS_TWEET
        with:
          message:  "${{ steps.parse.outputs.TWEET }}"
          twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}